### ISSUE TITLE
Round trip geometry columns

### ISSUE THREAD

**Issue by hadley** [r-dbi/RPostgres#114]
Using simple features

**Comment by etiennebr** [comment]
I'd like to give a hand, however I'm not sure how to do this properly, I'd appreciate if you could please advise me. 

I've thought of solutions relying on `dbWriteTable`. 

1. I believe we could update `get_data_type` to create the table with `geometry` type, but it uses `typeof`, which returns `list` for every custom object. Also I'm not sure that detecting `sfc` type belongs to RPostgres, so maybe you have another approach to suggest. This would ultimately enable to write `sfc` using `dbWriteTable`. I read discussion on DBI issues about handling custom formats, so there might be a solution coming?

2. Another option would be to expose the `value` argument in `sqlCreateTable` so we can properly override the default `BYTEA` for lists without needing to tweak `get_data_type`. Then we could use a custom `sf` writer such as current `st_read_db`. Something like:
```r
st_get_data_type <- function(obj) {
  if(inherits(obj, "sfc")) {
  	gtype <- st_geometry_type(obj)[1]
  	crs <- st_crs(obj)
  	d <- st_dimension(nc$geometry)[1]
    return(geom = paste0("geometry(", gtype, ",", crs[["epsg"]],",", d, ")"))
  }
  return(RPostgres:::get_data_type(obj))
}
#' This is a proposal, real function would require additional check of geometry type and dimension uniformity
```
If we could then pass a `vapply(sf, st_get_data_type, "")` to  `dbWriteTable`, then I believe we could create the table properly. Also, in favor of this approach is that prior to Posgis 2.0.0, the `geometry_columns` table had to be edited (e.g. using `AddGeometryColumn` which would be impossible using `dbWriteTable` directly. Though I think we can focus on post 2.0.0 as it will make it much simpler, but maybe something to consider.

3. Last option is to duplicate code form `dbWriteTable` in a `st_write_db`, then we can add whatever operation we need, but I believe `RPostgres` is meant to be pretty generic, so my understanding is that there is a way to make it work. Also other major issue is that it requires to rewrite the `st_write_db` for every driver, which would defy the purpose of a DBI, but might also be the pragmatic way. 

For reading the geometry, I'm not clear if type casting relies on `Rcpp::wrap`? If so, then I guess we'll have to rely on the current procedure: read > cast to text using dbRead > find geometry columns and crs from database > cast geometries to `sfc`.

**Comment by edzer** [comment]
The first thing you could do is make `RPostgres` recognize geometry columns; right now we see with RPostgres:
```r
> tb = dbReadTable(con, "meuse_sf")
Warning message:
In result_create(conn@ptr, statement) :
  Unknown field type (675587) in column wkb_geometry
```
and with RPostgreSQL:
```r
> tbl = dbReadTable(cc, "meuse_sf")
Warning message:
In postgresqlExecStatement(conn, statement, ...) :
  RS-DBI driver warning: (unrecognized PostgreSQL field type geometry (id:675587) in column 13)
```
which is even better, because the warning message mentions that the type is geometry.

Both functions return the WKB column as character:
```
> sapply(tb, class)
   row.names      cadmium       copper         lead         zinc         elev 
 "character"    "numeric"    "numeric"    "numeric"    "numeric"    "numeric" 
        dist           om        ffreq         soil         lime      landuse 
   "numeric"    "numeric"  "character"  "character"  "character"  "character" 
      dist.m wkb_geometry 
   "numeric"  "character" 
```
which is not very helpful downstream. Why not give it class `geometry`, or `WKB`? 

Right now, `sf` has an `st_as_sfc` method to read such data if it has class `WKB`:
```r
> st_as_sfc(structure(tbl[1:3,]$wkb_geometry, class = "WKB"), EWKB=TRUE)
Geometry set for 3 features 
geometry type:  POINT
dimension:      XY
bbox:           xmin: 181025 ymin: 333537 xmax: 181165 ymax: 333611
epsg (SRID):    28992
proj4string:    +proj=sterea +lat_0=52.15616055555555 +lon_0=5.38763888888889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel +towgs84=565.4171,50.3319,465.5524,-0.398957,0.343988,-1.87740,4.0725 +units=m +no_defs
POINT(181072 333611)
POINT(181025 333558)
POINT(181165 333537)
```

**Comment by etiennebr** [comment]
I believe the robust way to do this, would be to query the `pg_type` table. From my understanding, there is no guarantee that the `typelem` will be associated to a given `typname`.
For instance:
**etienne@postgis**
``` sql
select typname, typelem from pg_type where typname like '%geometry';
-- geometry  |       0
-- _geometry |   16391  
```
**etienne@etienne**
``` sql
select typname, typelem from pg_type where typname like '%geometry';
-- geometry  |       0
-- _geometry |   26423 
```
(Note that the real type is prefixed with `_`)

And @edzer, you got `675587`, on another database I got another number. I believe it depends on the  order of extension creation. This is probably why hard coded values work for simple types (they're create at databse creation in a deterministic order), but for extensions it will probably require to query the database. Once support for special types is enabled, then round-tripping is fairly easy. I think it's another issue, though.

**Comment by etiennebr** [comment]
Following #132, I'd like to declare geometry column round trip possible. However, we have to tolerate a warning for the unsupported geometry type when reading. 

I have the skeleton ready [for writing `sf` using `RPostgres`]https://github.com/r-spatial/sf/compare/master...etiennebr:RPostgres). For reading a geometry column, implementation depends on special type support (#132), but it works. 

I don't know what degree of readiness @hadley had in mind, nor what should be native to `RPostgres` versus `sf`. I'd say it works, but requires some tweaks on `RPostgres` to make it work really transparently.

**Comment by krlmlr** [comment]
Closing in favor of https://github.com/r-dbi/DBI/issues/203, let's continue discussion there with sf as a first application.

**Comment by krlmlr** [comment]
Geometry columns in PostgreSQL seem to be important enough to warrant built-in support, and it's easy enough to add it here:

- [ ] remove warning on unknown Oid, just return as string (that's how the data arrives anyway) perhaps with attribute
- [ ] we also export a helper function that returns known data types and their Oids from `pg_type`
- [ ] the Oid used for geometry columns is queried when connecting, appropriate action is taken

@etiennebr: Would you mind porting relevant parts of your code to RPostgres? Can we somehow return a generic data frame so that the sf package can automatically pick up the geometry column?

**Comment by etiennebr** [comment]
I'd be happy to do so. If either the data frame had a RPostgres type attribute with vector of types, or if each column had such an attribute, I think it would make it easy and generalize very well.

**Comment by krlmlr** [comment]
New plan:

- [ ] remove warning on unknown Oid, just return as string/blob (that's how the data arrives anyway) with a `class` attribute `c("pg_data_...", "pg_data", "character")` or `c("pg_data_...", "pg_data", "blob")`
- [ ] we load all known data types and Oids from `pg_type`
- [ ] we no longer look at hard-coded Oids but do all lookups dynamically

**Comment by hadley** [comment]
For performance, we’ll need to cache the oid table, right? Maybe once when the connection is established?

**Comment by krlmlr** [comment]
Yes, updated and reordered the list.

**Comment by etiennebr** [comment]
To my surprise, `RPostgreSQL` is querying for datatype (BTW it does not cache). In the database log I saw it generated statements for each row type `select typname, typcategory from pg_type where oid = 16392` after it executed the `SELECT * FROM "table" AS "zzz8" WHERE 0=1` from `dplyr`. I'll have a look at how they do it. 

I agree with caching, although there is a very corner case, where you could have types modified in the table after the connection is established. Since it doesn't happen very often, I think it's OK. New types could be looked up by refreshing cache (for instance you create a postgis extension after you connected, these would be re-queried).
