### ISSUE TITLE
Pros and cons against odbc?

### ISSUE THREAD

**Issue by vspinu** [r-dbi/RPostgres#240]
Sorry if it's not the right place to ask, but why would I choose RPostgres over odbc in a nutshell?

**Comment by Fredo-XVII** [comment]
The main reason why I love RPostgres is that you don't need to worry about setting up an odbc connection in you odbc manager if you are using Postgres.  I have built connection functions wrapping RPostgres.  It's also pretty fast for reading and writing.

Keep up the good work!

**Comment by vspinu** [comment]
@Fredo-XVII not sure what you mean by "setting up an odbc connection". I just do `DBI::dbConnect(odbc::odbc(), "connection_name")` where `connection_name` is declared in `.odbc.ini`. In fact for me this is the big advantage of using odbc because Rpostgres doesn't have such a config file.

**Comment by Fredo-XVII** [comment]
That's exactly my point; there is no config file to worry about on any
system. So you down load it and your off to the races. No odbc.ini file to
have to maintain.

When you create a "connection name" you do it for each specific database
you want to connect to. With RPostgres, you specify the database in the
connection string.

**Comment by rtrad89** [comment]
Even with `RPostgres` one can still use a separate `YML` configuration file *on the application level* to store connection-strings rather than divulging them in the code; see [this](https://db.rstudio.com/best-practices/managing-credentials/#stored-in-a-file-with-config).

**Comment by tyluRp** [comment]
Bumping, I would also be interested in some documentation on the pros and cons. I just found out that RPostgres will write a table significantly faster than odbc because of COPY vs INSERT. I'm curious if there are any other benefits!

**Comment by zozlak** [comment]
Theoretically there is only one important difference - everything going trough the ODBC must fit the ODBC data model.
It means no vendor-specific features and optimizations can be used with ODBC.

The question is does it make a difference for you.

A quick list of features which don't play well with the ODBC data model:

* `COPY` statement for fast bulk data import. Nothing like that in the ODBC and `INSERT`s are slow.
* Large objects. There is some support for them in Postgresql ODBC driver but it differs a lot from how you handle it natively.
* Any datatype which doesn't fit the [list of ODBC datatypes](https://docs.microsoft.com/en-us/sql/odbc/reference/appendixes/c-data-types?view=sql-server-ver15). Which by today standards is very short and (what's worse) written in stone. It might sound strange - who needs more than varchar, int and float - but judging from my experience as a former RODBCext package maintainer most problems users reported were data types mapping issues. And as currently RDBMSs turn more and more into multi-paradigm DBMSs (Postgresql being no exception) this might become more and more important.
  * From Postgresql perspective the very first candidate for problems is the `text` data type. If you really store long strings in it, you will have troubles with ODBC.
  * It would require testing but I guess dates outside of usual range may cause trouble in ODBC (because of differences in storage ranges assumed in ODBC and particular db vendors).
  * If you want better integration of non-standard data type and you are good enough at programming, you can add it to the vendor-specific driver but there are no means to do it in the ODBC (as the ODBC driver hides the "real" data type from you).
    * E.g. I can imagine adding support for Postgresql arrays or JSON to RPostgres once I consider it a feature I need but it's impossible by design in the ODBC.
    * If you are lucky, support for some of them might be already provided by a "native" package but I have no idea of what is and what isn't supported by the RPostgres.
* No `LISTEN/NOTIFY` in ODBC.

Despite that:

* As any other virtualization layer ODBC brings some performance penalty. But honestly it's probably nothing you would care about.
* Don't have any hard evidence on that but based on my experience I would say native packages are slightly more stable.

That being said if you don't care about vendor-specific features (most users probably don't), using ODBC has one big advantage - promises portability of your code to another database vendor.
Everyone who tried it in practice knows there are caveats but it's definitely easier while using ODBC than without (as ODBC prevents you from using vendor-specific features and the only problem you need to solve are differences between ODBC drivers behavior).

**Comment by jjesusfilho** [comment]
As a matter of fact, PostgreSQL also allows you to keep a [connection file](https://www.postgresql.org/docs/current/libpq-pgservice.html). I have been using it: ```conn <- DBI::dbConnect(RPostgres::Postgres(), service = "mydb_or_project")```

**Comment by krlmlr** [comment]
Thanks @zozlak for the summary. I'm hesitant to add this info to this package's documentation, we'd need to copy in RMariaDB and perhaps other backends. Maybe this would be a fit for the odbc package? Or we could link to content hosted elsewhere.

**Comment by krlmlr** [comment]
Filed two issues elsewhere.
